apiVersion: apps/v1
kind: Deployment
metadata: 
  name: medium-rare-article
spec:
  replicas: 1
  minReadySeconds: 100
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: article
  template:
    metadata:
      name: article
      labels:
        app: article
    spec:
      containers:
      - image: kbzjung359/medium-rare-article:0.0.2-arm64
        name: gin-article
        envFrom:
        - configMapRef:
            name: medium-configmap
        ports:
        - containerPort: 8082
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /healthy
            port: 8082
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /healthy
            port: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: medium-rare-article
spec:
  type: NodePort
  selector:
    app: article
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30082
