apiVersion: apps/v1
kind: Deployment
metadata: 
  name: medium-rare-reading
spec:
  replicas: 1
  minReadySeconds: 100
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: reading
  template:
    metadata:
      name: reading
      labels:
        app: reading
    spec:
      containers:
      - image: kbzjung359/medium-rare-reading:0.0.2-arm64
        name: gin-reading
        envFrom:
        - configMapRef:
            name: medium-configmap
        ports:
        - containerPort: 8083
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /healthy
            port: 8083
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /ready
            port: 8083          
---
apiVersion: v1
kind: Service
metadata:
  name: medium-rare-reading
spec:
  type: NodePort
  selector:
    app: reading
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30083
