apiVersion: apps/v1
kind: Deployment
metadata: 
  name: medium-rare-trend
spec:
  replicas: 1
  minReadySeconds: 100
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: trend
  template:
    metadata:
      name: trend
      labels:
        app: trend
    spec:
      containers:
      - image: kbzjung359/medium-rare-trend:0.0.2-arm64
        name: gin-trend
        envFrom:
        - configMapRef:
            name: medium-configmap
        ports:
        - containerPort: 8084
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /healthy
            port: 8084
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /ready
            port: 8084          
---
apiVersion: v1
kind: Service
metadata:
  name: medium-rare-trend
spec:
  type: NodePort
  selector:
    app: trend
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30084
