apiVersion: apps/v1
kind: Deployment
metadata: 
  name: medium-rare-user
spec:
  replicas: 1
  minReadySeconds: 100
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      name: user
      labels:
        app: user
    spec:
      containers:
      - image: kbzjung359/medium-rare-user:0.0.2-arm64
        name: gin-user
        envFrom:
        - configMapRef:
            name: medium-configmap
        ports:
        - containerPort: 8081
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /healthy
            port: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /healthy
            port: 8081      
---
apiVersion: v1
kind: Service
metadata:
  name: medium-rare-user
spec:
  type: NodePort
  selector:
    app: user
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
